### ISSUE TITLE
Cannot instantiate form schemas 

### ISSUE THREAD

**Issue by timriley** [dryrb/dry-validation#16]
Looks like there's an issue preventing form schemas from being instantiated. I get this when I copy/paste/run your `examples/form.rb` code:

```ruby
class UserFormSchema < Dry::Validation::Schema::Form
  key(:email) { |value| value.str? & value.filled? }

  key(:age) { |value| value.int? & value.gt?(18) }
end
```

```
[12] pry(main)> schema = UserFormSchema.new
NoMethodError: undefined method `visit_string' for #<Dry::Data::Compiler:0x007fa59d915c68 @registry=Dry::Data>
from /Users/tim/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/dry-data-6aa35ff8de9c/lib/dry/data/compiler.rb:15:in `visit'
```

I'm using the latest from github on both dry-validation and dry-data. Full stacktrace here:

```
Exception: NoMethodError: undefined method `visit_string' for #<Dry::Data::Compiler:0x007fac72da9820 @registry=Dry::Data>
--
 0: /Users/tim/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/dry-data-6aa35ff8de9c/lib/dry/data/compiler.rb:15:in `visit'
 1: /Users/tim/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/dry-data-6aa35ff8de9c/lib/dry/data/compiler.rb:39:in `visit_key'
 2: /Users/tim/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/dry-data-6aa35ff8de9c/lib/dry/data/compiler.rb:15:in `visit'
 3: /Users/tim/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/dry-data-6aa35ff8de9c/lib/dry/data/compiler.rb:34:in `block in visit_hash'
 4: /Users/tim/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/dry-data-6aa35ff8de9c/lib/dry/data/compiler.rb:34:in `map'
 5: /Users/tim/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/dry-data-6aa35ff8de9c/lib/dry/data/compiler.rb:34:in `visit_hash'
 6: /Users/tim/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/dry-data-6aa35ff8de9c/lib/dry/data/compiler.rb:22:in `visit_type'
 7: /Users/tim/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/dry-data-6aa35ff8de9c/lib/dry/data/compiler.rb:15:in `visit'
 8: /Users/tim/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/dry-data-6aa35ff8de9c/lib/dry/data/compiler.rb:11:in `call'
 9: /Users/tim/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/dry-validation-fb344cc0b4d4/lib/dry/validation/input_type_compiler.rb:19:in `call'
10: /Users/tim/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/dry-validation-fb344cc0b4d4/lib/dry/validation/schema/form.rb:11:in `initialize'
11: (pry):8:in `new'
12: (pry):8:in `<main>'
```

I'm _just_ getting started with trying out dry-validation, so I hope this is enough info for you to go on!

**Comment by solnic** [comment]
This works now:

``` ruby
require 'dry-validation'
require 'dry/validation/schema/form'

class UserFormSchema < Dry::Validation::Schema::Form
  key(:email) { |value| value.str? & value.filled? }

  key(:age) { |value| value.int? & value.gt?(18) }
end

puts UserFormSchema.new.messages('email' => '', 'age' => 19).inspect
# #<Dry::Validation::Schema::Result params={"email"=>"", "age"=>19} errors=[[:email, ["email must be filled"]]]>
```
