### ISSUE TITLE
Array validation crashes

### ISSUE THREAD

**Issue by kirs** [dryrb/dry-validation#42]
Array validation is expected to return validation error if value is *not* an array, but now it crashes.

dry-validation 0.4.1
dry-data 0.4.2

```ruby
class Schema < Dry::Validation::Schema::Form
  key(:email) { |email| email.filled? }
  key(:ids) do |v|
    v.array? do
      v.each(&:int?)
    end
  end
end

# works
Schema.new.call({
  "email" => "filled",
  "ids" => ["1", "2", "3"]
})

# expected to return validation error bug crashes
Schema.new.call({
  "email" => "filled",
  "ids" => "not_ids"
})

# /Users/kir/Projects/opensource/dry-params/vendor/bundle/gems/dry-data-0.4.2/lib/dry/data/type/array.rb:6:in `constructor': undefined method `map' for "not_ids":String (NoMethodError)
# 	from /Users/kir/Projects/opensource/dry-params/vendor/bundle/gems/dry-data-0.4.2/lib/dry/data/type.rb:74:in `call'
# 	from /Users/kir/Projects/opensource/dry-params/vendor/bundle/gems/dry-data-0.4.2/lib/dry/data/type/hash.rb:22:in `block in symbolized_constructor'
# 	from /Users/kir/Projects/opensource/dry-params/vendor/bundle/gems/dry-data-0.4.2/lib/dry/data/type/hash.rb:18:in `each'
# 	from /Users/kir/Projects/opensource/dry-params/vendor/bundle/gems/dry-data-0.4.2/lib/dry/data/type/hash.rb:18:in `each_with_object'
# 	from /Users/kir/Projects/opensource/dry-params/vendor/bundle/gems/dry-data-0.4.2/lib/dry/data/type/hash.rb:18:in `symbolized_constructor'
# 	from /Users/kir/Projects/opensource/dry-params/vendor/bundle/gems/dry-data-0.4.2/lib/dry/data/type.rb:74:in `call'
# 	from /Users/kir/Projects/opensource/dry-params/vendor/bundle/gems/dry-validation-0.4.1/lib/dry/validation/schema/form.rb:15:in `call'
# 	from bug.rb:23:in `<main>'

```

**Comment by kirs** [comment]
As I found, it crashes only with `Dry::Validation::Schema::Form`. `Dry::Validation::Schema` works fine. /cc @solnic

**Comment by solnic** [comment]
Thanks for the bug report. I'll fix it in the next version.
